# Form implementation generated from reading ui file 'C:\Users\PC\PycharmProjects\오목봇\main_code\GomokuBoardEditor.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(parent=self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(0, 0, 321, 41))
        font = QtGui.QFont()
        font.setFamily("둥근모꼴")
        font.setPointSize(36)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.Board = QtWidgets.QLabel(parent=self.centralwidget)
        self.Board.setGeometry(QtCore.QRect(300, 50, 441, 441))
        self.Board.setText("")
        self.Board.setPixmap(QtGui.QPixmap("img/Board.jpg"))
        self.Board.setScaledContents(True)
        self.Board.setObjectName("Board")
        self.BlackStone = QtWidgets.QLabel(parent=self.centralwidget)
        self.BlackStone.setGeometry(QtCore.QRect(511, 259, 21, 21))
        self.BlackStone.setText("")
        self.BlackStone.setPixmap(QtGui.QPixmap("img/BlackStone.png"))
        self.BlackStone.setScaledContents(True)
        self.BlackStone.setObjectName("BlackStone")
        self.WhiteStone = QtWidgets.QLabel(parent=self.centralwidget)
        self.WhiteStone.setGeometry(QtCore.QRect(539, 260, 21, 21))
        self.WhiteStone.setText("")
        self.WhiteStone.setPixmap(QtGui.QPixmap("img/WhiteStone.png"))
        self.WhiteStone.setScaledContents(True)
        self.WhiteStone.setObjectName("WhiteStone")
        self.subtitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.subtitle.setGeometry(QtCore.QRect(0, 40, 301, 21))
        font = QtGui.QFont()
        font.setFamily("둥근모꼴")
        font.setPointSize(12)
        self.subtitle.setFont(font)
        self.subtitle.setObjectName("subtitle")
        self.Desctription1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Desctription1.setGeometry(QtCore.QRect(0, 90, 301, 121))
        font = QtGui.QFont()
        font.setFamily("둥근모꼴")
        font.setPointSize(12)
        self.Desctription1.setFont(font)
        self.Desctription1.setObjectName("Desctription1")
        self.MYNAME = QtWidgets.QLabel(parent=self.centralwidget)
        self.MYNAME.setGeometry(QtCore.QRect(660, 490, 131, 61))
        font = QtGui.QFont()
        font.setFamily("둥근모꼴")
        font.setPointSize(36)
        self.MYNAME.setFont(font)
        self.MYNAME.setObjectName("MYNAME")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.actionSave_As = QtGui.QAction(parent=MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")

        self.actionDrag_or_Click = QtGui.QAction(parent=MainWindow)
        self.actionDrag_or_Click.setObjectName("actionDrag_or_Click")

        self.actionLoad = QtGui.QAction(parent=MainWindow)
        self.actionLoad.setObjectName("actionLoad")

        self.actionReset = QtGui.QAction(parent=MainWindow)
        self.actionReset.setObjectName("actionReset")

        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Title.setText(_translate("MainWindow", "Gomoku Board"))
        self.subtitle.setText(_translate("MainWindow", "개쩌는 오목 타일 에디아터임!@!!!"))
        self.Desctription1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">How to use:</span></p><p>매우 쉬움!<br/>FIle에서 저장 버튼을 누르면</p><p>저장이 되고요</p><p>로드를 누르면 로드가 됩니다!</p><p>좌/우 클 각각 백돌흑돌</p><p>스페이스바 마커설치</p></body></html>"))
        self.MYNAME.setText(_translate("MainWindow", "By YJ"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As.."))
        self.actionDrag_or_Click.setText(_translate("MainWindow", "Drag or Click"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionReset.setText(_translate("MainWindow", "지금 바로 윤회"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
